imports:
  - https://raw.githubusercontent.com/dotnet/crank/master/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  mvc:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: halter73/mapaction
      project: src/BenchmarksApps/Mvc/Mvc.csproj
    readyStateText: Application started.
  uController:
    source:
      repository: https://github.com/halter73/uController.git
      branchOrCommit: master
      project: Samples/Samples.csproj
    readyStateText: Application started.

scenarios:
  post-echo-controller:
    application:
      job: mvc
    load:
      job: bombardier
      variables:
        path: /EchoController
        verb: 'POST --header "Content-Type: application/json"'
        bodyFile: https://raw.githubusercontent.com/aspnet/benchmarks/halter73/mapaction/scenarios/person.json
  post-echo-routerware:
    application:
      job: mvc
    load:
      job: bombardier
      variables:
        path: /EchoAction
        verb: 'POST --header "Content-Type: application/json"'
        bodyFile: https://raw.githubusercontent.com/aspnet/benchmarks/halter73/mapaction/scenarios/person.json
  post-echo-ucontroller:
    application:
      job: uController
    load:
      job: bombardier
      variables:
        path: /
        verb: 'POST --header "Content-Type: application/json"'
        bodyFile: https://raw.githubusercontent.com/aspnet/benchmarks/halter73/mapaction/scenarios/person.json
  get-echo-controller:
    application:
      job: mvc
    load:
      job: bombardier
      variables:
        path: /EchoController/Stephen
  get-echo-routerware:
    application:
      job: mvc
    load:
      job: bombardier
      variables:
        path: /EchoAction/Stephen
  get-output-controller:
    application:
      job: mvc
    load:
      job: bombardier
      variables:
        path: /EchoController
  get-output-routerware:
    application:
      job: mvc
    load:
      job: bombardier
      variables:
        path: /EchoAction

profiles:
  aspnet-perf-lin:
    variables:
      serverAddress: 10.0.0.102
      cores: 12
    jobs:
      application:
        endpoints:
          - http://asp-perf-lin:5001
      load:
        endpoints:
          - http://asp-perf-load:5001
        options:
          displayOutput: true